### ISSUE TITLE
Can't build the 2.3.1: failed compiling file:src/cats/monad/state.cljc

### ISSUE THREAD

**Issue by Bost** [funcool/cats#224]
```
$ git checkout 2.3.1
# ...
$ git clean -dxf
# ...
$ ./scripts/build 
WARNING: boolean? already refers to: #'clojure.core/boolean? in namespace: fipp.visit, being replaced by: #'fipp.visit/boolean?
Building ...
Copying jar:file:/home/bost/.m2/repository/org/clojure/clojurescript/1.9.946/clojurescript-1.9.946.jar!/cljs/core.cljs to out/cljs/core.cljs
Reading analysis cache for jar:file:/home/bost/.m2/repository/org/clojure/clojurescript/1.9.946/clojurescript-1.9.946.jar!/cljs/core.cljs
Compiling out/cljs/core.cljs
Using cached cljs.core out/cljs/core.cljs
Copying jar:file:/home/bost/.m2/repository/org/clojure/test.check/0.9.0/test.check-0.9.0.jar!/clojure/test/check/impl.cljc to out/clojure/test/check/impl.cljc
Compiling out/clojure/test/check/impl.cljc
Copying jar:file:/home/bost/.m2/repository/org/clojure/clojurescript/1.9.946/clojurescript-1.9.946.jar!/clojure/string.cljs to out/clojure/string.cljs
Compiling out/clojure/string.cljs
Copying jar:file:/home/bost/.m2/repository/org/clojure/clojurescript/1.9.946/clojurescript-1.9.946.jar!/cljs/pprint.cljs to out/cljs/pprint.cljs
Compiling out/cljs/pprint.cljs
Copying jar:file:/home/bost/.m2/repository/org/clojure/clojurescript/1.9.946/clojurescript-1.9.946.jar!/cljs/test.cljs to out/cljs/test.cljs
Compiling out/cljs/test.cljs
Copying jar:file:/home/bost/.m2/repository/org/clojure/test.check/0.9.0/test.check-0.9.0.jar!/clojure/test/check/clojure_test.cljc to out/clojure/test/check/clojure_test.cljc
Compiling out/clojure/test/check/clojure_test.cljc
Compiling src/cats/protocols.cljc
Compiling /home/bost/dec/cats/src/cats/context.cljc
Copying jar:file:/home/bost/.m2/repository/org/clojure/clojurescript/1.9.946/clojurescript-1.9.946.jar!/clojure/set.cljs to out/clojure/set.cljs
Compiling out/clojure/set.cljs
Compiling src/cats/core.cljc
Compiling /home/bost/dec/cats/src/cats/util.cljc
Compiling /home/bost/dec/cats/src/cats/monad/maybe.cljc
Compiling src/cats/builtin.cljc
Copying jar:file:/home/bost/.m2/repository/org/clojure/test.check/0.9.0/test.check-0.9.0.jar!/clojure/test/check/rose_tree.cljc to out/clojure/test/check/rose_tree.cljc
Compiling out/clojure/test/check/rose_tree.cljc
Copying jar:file:/home/bost/.m2/repository/org/clojure/test.check/0.9.0/test.check-0.9.0.jar!/clojure/test/check/random/longs/bit_count_impl.cljs to out/clojure/test/check/random/longs/bit_count_impl.cljs
Compiling out/clojure/test/check/random/longs/bit_count_impl.cljs
Copying jar:file:/home/bost/.m2/repository/org/clojure/test.check/0.9.0/test.check-0.9.0.jar!/clojure/test/check/random/longs.cljs to out/clojure/test/check/random/longs.cljs
Compiling out/clojure/test/check/random/longs.cljs
Copying jar:file:/home/bost/.m2/repository/org/clojure/test.check/0.9.0/test.check-0.9.0.jar!/clojure/test/check/random/doubles.cljs to out/clojure/test/check/random/doubles.cljs
Compiling out/clojure/test/check/random/doubles.cljs
Copying jar:file:/home/bost/.m2/repository/org/clojure/test.check/0.9.0/test.check-0.9.0.jar!/clojure/test/check/random.cljs to out/clojure/test/check/random.cljs
Compiling out/clojure/test/check/random.cljs
Copying jar:file:/home/bost/.m2/repository/org/clojure/test.check/0.9.0/test.check-0.9.0.jar!/clojure/test/check/generators.cljc to out/clojure/test/check/generators.cljc
Compiling out/clojure/test/check/generators.cljc
Copying jar:file:/home/bost/.m2/repository/org/clojure/test.check/0.9.0/test.check-0.9.0.jar!/clojure/test/check.cljc to out/clojure/test/check.cljc
Compiling out/clojure/test/check.cljc
Copying jar:file:/home/bost/.m2/repository/org/clojure/test.check/0.9.0/test.check-0.9.0.jar!/clojure/test/check/properties.cljc to out/clojure/test/check/properties.cljc
Compiling out/clojure/test/check/properties.cljc
Compiling /home/bost/dec/cats/src/cats/labs/test.cljc
Copying jar:file:/home/bost/.m2/repository/org/clojure/core.match/0.3.0-alpha4/core.match-0.3.0-alpha4.jar!/cljs/core/match.cljs to out/cljs/core/match.cljs
Compiling out/cljs/core/match.cljs
Compiling src/cats/monad/either.cljc
Compiling test/cats/monad/either_spec.cljc
Compiling test/cats/monad/maybe_spec.cljc
Copying jar:file:/home/bost/.m2/repository/org/clojure/core.async/0.4.474/core.async-0.4.474.jar!/cljs/core/async/impl/protocols.cljs to out/cljs/core/async/impl/protocols.cljs
Compiling out/cljs/core/async/impl/protocols.cljs
Copying jar:file:/home/bost/.m2/repository/org/clojure/core.async/0.4.474/core.async-0.4.474.jar!/cljs/core/async/impl/buffers.cljs to out/cljs/core/async/impl/buffers.cljs
Compiling out/cljs/core/async/impl/buffers.cljs
Copying jar:file:/home/bost/.m2/repository/org/clojure/core.async/0.4.474/core.async-0.4.474.jar!/cljs/core/async/impl/dispatch.cljs to out/cljs/core/async/impl/dispatch.cljs
Compiling out/cljs/core/async/impl/dispatch.cljs
Copying jar:file:/home/bost/.m2/repository/org/clojure/core.async/0.4.474/core.async-0.4.474.jar!/cljs/core/async/impl/channels.cljs to out/cljs/core/async/impl/channels.cljs
Compiling out/cljs/core/async/impl/channels.cljs
Copying jar:file:/home/bost/.m2/repository/org/clojure/core.async/0.4.474/core.async-0.4.474.jar!/cljs/core/async/impl/ioc_helpers.cljs to out/cljs/core/async/impl/ioc_helpers.cljs
Compiling out/cljs/core/async/impl/ioc_helpers.cljs
Copying jar:file:/home/bost/.m2/repository/org/clojure/core.async/0.4.474/core.async-0.4.474.jar!/cljs/core/async/impl/timers.cljs to out/cljs/core/async/impl/timers.cljs
Compiling out/cljs/core/async/impl/timers.cljs
Copying jar:file:/home/bost/.m2/repository/org/clojure/core.async/0.4.474/core.async-0.4.474.jar!/cljs/core/async.cljs to out/cljs/core/async.cljs
Compiling out/cljs/core/async.cljs
Compiling src/cats/labs/channel.cljc
Compiling test/cats/labs/channel_spec.cljc
Copying jar:file:/home/bost/.m2/repository/funcool/promesa/1.9.0/promesa-1.9.0.jar!/promesa/protocols.cljc to out/promesa/protocols.cljc
Compiling out/promesa/protocols.cljc
Copying jar:file:/home/bost/.m2/repository/funcool/promesa/1.9.0/promesa-1.9.0.jar!/promesa/impl.cljc to out/promesa/impl.cljc
Compiling out/promesa/impl.cljc
Copying jar:file:/home/bost/.m2/repository/funcool/promesa/1.9.0/promesa-1.9.0.jar!/promesa/impl/scheduler.cljc to out/promesa/impl/scheduler.cljc
Compiling out/promesa/impl/scheduler.cljc
Copying jar:file:/home/bost/.m2/repository/funcool/promesa/1.9.0/promesa-1.9.0.jar!/promesa/core.cljc to out/promesa/core.cljc
Compiling out/promesa/core.cljc
Compiling src/cats/monad/exception.cljc
Compiling /home/bost/dec/cats/src/cats/labs/promise.cljc
Compiling /home/bost/dec/cats/test/cats/labs/promise_spec.cljc
Compiling /home/bost/dec/cats/src/cats/monad/identity.cljc
Compiling /home/bost/dec/cats/test/cats/monad/identity_spec.cljc
Compiling test/cats/monad/exception_spec.cljc
Compiling /home/bost/dec/cats/test/cats/core_spec.cljc
Compiling src/cats/data.cljc
Compiling test/cats/data_spec.cljc
Compiling /home/bost/dec/cats/test/cats/builtin_spec.cljc
Compiling src/cats/monad/state.cljc
Exception in thread "main" clojure.lang.ExceptionInfo: failed compiling file:src/cats/monad/state.cljc {:file #object[java.io.File 0x47019cef "src/cats/monad/state.cljc"]}, compiling:(/home/bost/dec/cats/scripts/build.clj:5:1)
	at clojure.lang.Compiler.load(Compiler.java:7526)
	at clojure.lang.Compiler.loadFile(Compiler.java:7452)
	at clojure.main$load_script.invokeStatic(main.clj:278)
	at clojure.main$script_opt.invokeStatic(main.clj:338)
	at clojure.main$script_opt.invoke(main.clj:333)
	at clojure.main$main.invokeStatic(main.clj:424)
	at clojure.main$main.doInvoke(main.clj:387)
	at clojure.lang.RestFn.applyTo(RestFn.java:137)
	at clojure.lang.Var.applyTo(Var.java:702)
	at clojure.main.main(main.java:37)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at clojure.lang.Reflector.invokeMatchingMethod(Reflector.java:93)
	at clojure.lang.Reflector.invokeStaticMethod(Reflector.java:207)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at clojure.lang.Reflector.invokeMatchingMethod(Reflector.java:93)
	at clojure.lang.Reflector.invokeStaticMethod(Reflector.java:207)
	at user$eval2650.invokeStatic(form-init2760537289329875838.clj:1)
	at user$eval2650.invoke(form-init2760537289329875838.clj:1)
	at clojure.lang.Compiler.eval(Compiler.java:7062)
	at clojure.lang.Compiler.eval(Compiler.java:7052)
	at clojure.lang.Compiler.load(Compiler.java:7514)
	at clojure.lang.Compiler.loadFile(Compiler.java:7452)
	at clojure.main$load_script.invokeStatic(main.clj:278)
	at clojure.main$init_opt.invokeStatic(main.clj:280)
	at clojure.main$init_opt.invoke(main.clj:280)
	at clojure.main$initialize.invokeStatic(main.clj:311)
	at clojure.main$null_opt.invokeStatic(main.clj:345)
	at clojure.main$null_opt.invoke(main.clj:342)
	at clojure.main$main.invokeStatic(main.clj:424)
	at clojure.main$main.doInvoke(main.clj:387)
	at clojure.lang.RestFn.applyTo(RestFn.java:137)
	at clojure.lang.Var.applyTo(Var.java:702)
	at clojure.main.main(main.java:37)
Caused by: clojure.lang.ExceptionInfo: failed compiling file:src/cats/monad/state.cljc {:file #object[java.io.File 0x47019cef "src/cats/monad/state.cljc"]}
	at clojure.core$ex_info.invokeStatic(core.clj:4739)
	at clojure.core$ex_info.invoke(core.clj:4739)
	at cljs.compiler$compile_file$fn__7101.invoke(compiler.cljc:1552)
	at cljs.compiler$compile_file.invokeStatic(compiler.cljc:1513)
	at cljs.compiler$compile_file.invoke(compiler.cljc:1489)
	at cljs.closure$compile_file.invokeStatic(closure.clj:540)
	at cljs.closure$compile_file.invoke(closure.clj:531)
	at cljs.closure$eval9356$fn__9357.invoke(closure.clj:609)
	at cljs.closure$eval9292$fn__9293$G__9281__9300.invoke(closure.clj:493)
	at cljs.closure$compile_sources$iter__9480__9484$fn__9485.invoke(closure.clj:954)
	at clojure.lang.LazySeq.sval(LazySeq.java:40)
	at clojure.lang.LazySeq.seq(LazySeq.java:49)
	at clojure.lang.Cons.next(Cons.java:39)
	at clojure.lang.RT.next(RT.java:706)
	at clojure.core$next__5108.invokeStatic(core.clj:64)
	at clojure.core$dorun.invokeStatic(core.clj:3134)
	at clojure.core$doall.invokeStatic(core.clj:3140)
	at clojure.core$doall.invoke(core.clj:3140)
	at cljs.closure$compile_sources.invokeStatic(closure.clj:950)
	at cljs.closure$compile_sources.invoke(closure.clj:939)
	at cljs.closure$build.invokeStatic(closure.clj:2596)
	at cljs.closure$build.invoke(closure.clj:2507)
	at cljs.build.api$build.invokeStatic(api.clj:205)
	at cljs.build.api$build.invoke(api.clj:189)
	at cljs.build.api$build.invokeStatic(api.clj:192)
	at cljs.build.api$build.invoke(api.clj:189)
	at user$eval10285.invokeStatic(build.clj:6)
	at user$eval10285.invoke(build.clj:5)
	at clojure.lang.Compiler.eval(Compiler.java:7062)
	at clojure.lang.Compiler.load(Compiler.java:7514)
	... 38 more
Caused by: clojure.lang.ExceptionInfo: No such namespace: cats.data.Pair, could not locate cats/data/Pair.cljs, cats/data/Pair.cljc, or JavaScript source providing "cats.data.Pair" in file src/cats/monad/state.cljc {:tag :cljs/analysis-error}
	at clojure.core$ex_info.invokeStatic(core.clj:4739)
	at clojure.core$ex_info.invoke(core.clj:4739)
	at cljs.analyzer$error.invokeStatic(analyzer.cljc:697)
	at cljs.analyzer$error.invoke(analyzer.cljc:693)
	at cljs.analyzer$error.invokeStatic(analyzer.cljc:695)
	at cljs.analyzer$error.invoke(analyzer.cljc:693)
	at cljs.analyzer$analyze_deps.invokeStatic(analyzer.cljc:2128)
	at cljs.analyzer$analyze_deps.invoke(analyzer.cljc:2102)
	at cljs.analyzer$ns_side_effects.invokeStatic(analyzer.cljc:3467)
	at cljs.analyzer$ns_side_effects.invoke(analyzer.cljc:3462)
	at cljs.analyzer$analyze_STAR_$fn__5812.invoke(analyzer.cljc:3586)
	at clojure.lang.PersistentVector.reduce(PersistentVector.java:341)
	at clojure.core$reduce.invokeStatic(core.clj:6747)
	at clojure.core$reduce.invoke(core.clj:6730)
	at cljs.analyzer$analyze_STAR_.invokeStatic(analyzer.cljc:3586)
	at cljs.analyzer$analyze_STAR_.invoke(analyzer.cljc:3576)
	at cljs.analyzer$analyze.invokeStatic(analyzer.cljc:3610)
	at cljs.analyzer$analyze.invoke(analyzer.cljc:3593)
	at cljs.compiler$emit_source.invokeStatic(compiler.cljc:1377)
	at cljs.compiler$emit_source.invoke(compiler.cljc:1356)
	at cljs.compiler$compile_file_STAR_$fn__7070.invoke(compiler.cljc:1456)
	at cljs.compiler$with_core_cljs.invokeStatic(compiler.cljc:1271)
	at cljs.compiler$with_core_cljs.invoke(compiler.cljc:1260)
	at cljs.compiler$compile_file_STAR_.invokeStatic(compiler.cljc:1441)
	at cljs.compiler$compile_file_STAR_.invoke(compiler.cljc:1434)
	at cljs.compiler$compile_file$fn__7101.invoke(compiler.cljc:1538)
	... 65 more
```

**Comment by Bost** [comment]
Now it compiles under:
```
$ java -version
openjdk version "1.8.0_191"
OpenJDK Runtime Environment (build 1.8.0_191-8u191-b12-0ubuntu0.18.04.1-b12)
OpenJDK 64-Bit Server VM (build 25.191-b12, mixed mode)
```
Thank you(!), but it does not compile under:
```
$ java -version
openjdk version "10.0.2" 2018-07-17
OpenJDK Runtime Environment (build 10.0.2+13-Ubuntu-1ubuntu0.18.04.4)
OpenJDK 64-Bit Server VM (build 10.0.2+13-Ubuntu-1ubuntu0.18.04.4, mixed mode)
$ git log -1
commit 657f4a7e388a67c23d0064023f1ae693ccfdc958 (HEAD -> master, origin/master)
Merge: d96c80a 86a20d9
Author: ericvm <ericvm@users.noreply.github.com>
Date:   Wed Nov 28 11:59:32 2018 -0200

    Merge pull request #225 from Saityi/issue224
    
    Update pair type import to work in cljc
$ git log -1
commit 657f4a7e388a67c23d0064023f1ae693ccfdc958 (HEAD -> master, origin/master)
Merge: d96c80a 86a20d9
Author: ericvm <ericvm@users.noreply.github.com>
Date:   Wed Nov 28 11:59:32 2018 -0200

    Merge pull request #225 from Saityi/issue224
    
    Update pair type import to work in cljc
$ git clean -dxf
$ ./scripts/build 
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by mranderson048.orchard.v0v3v0.dynapath.v0v2v5.dynapath.defaults$eval1618$fn__1619 to method java.net.URLClassLoader.addURL(java.net.URL)
WARNING: Please consider reporting this to the maintainers of mranderson048.orchard.v0v3v0.dynapath.v0v2v5.dynapath.defaults$eval1618$fn__1619
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
WARNING: boolean? already refers to: #'clojure.core/boolean? in namespace: fipp.visit, being replaced by: #'fipp.visit/boolean?
Exception in thread "main" java.lang.ClassNotFoundException: javax.xml.bind.DatatypeConverter, compiling:(cljs/util.cljc:1:1)
	at clojure.lang.Compiler.load(Compiler.java:7526)
	at clojure.lang.RT.loadResourceScript(RT.java:379)
	at clojure.lang.RT.loadResourceScript(RT.java:370)
	at clojure.lang.RT.load(RT.java:460)
	at clojure.lang.RT.load(RT.java:426)
	at clojure.core$load$fn__6548.invoke(core.clj:6046)
	at clojure.core$load.invokeStatic(core.clj:6045)
	at clojure.core$load.doInvoke(core.clj:6029)
	at clojure.lang.RestFn.invoke(RestFn.java:408)
	at clojure.core$load_one.invokeStatic(core.clj:5848)
	at clojure.core$load_one.invoke(core.clj:5843)
	at clojure.core$load_lib$fn__6493.invoke(core.clj:5888)
	at clojure.core$load_lib.invokeStatic(core.clj:5887)
	at clojure.core$load_lib.doInvoke(core.clj:5868)
	at clojure.lang.RestFn.applyTo(RestFn.java:142)
	at clojure.core$apply.invokeStatic(core.clj:659)
	at clojure.core$load_libs.invokeStatic(core.clj:5925)
	at clojure.core$load_libs.doInvoke(core.clj:5909)
	at clojure.lang.RestFn.applyTo(RestFn.java:137)
	at clojure.core$apply.invokeStatic(core.clj:659)
	at clojure.core$require.invokeStatic(core.clj:5947)
	at clojure.core$require.doInvoke(core.clj:5947)
	at clojure.lang.RestFn.invoke(RestFn.java:703)
	at cljs.build.api$eval2671$loading__6434__auto____2672.invoke(api.clj:8)
	at cljs.build.api$eval2671.invokeStatic(api.clj:8)
	at cljs.build.api$eval2671.invoke(api.clj:8)
	at clojure.lang.Compiler.eval(Compiler.java:7062)
	at clojure.lang.Compiler.eval(Compiler.java:7051)
	at clojure.lang.Compiler.load(Compiler.java:7514)
	at clojure.lang.RT.loadResourceScript(RT.java:379)
	at clojure.lang.RT.loadResourceScript(RT.java:370)
	at clojure.lang.RT.load(RT.java:460)
	at clojure.lang.RT.load(RT.java:426)
	at clojure.core$load$fn__6548.invoke(core.clj:6046)
	at clojure.core$load.invokeStatic(core.clj:6045)
	at clojure.core$load.doInvoke(core.clj:6029)
	at clojure.lang.RestFn.invoke(RestFn.java:408)
	at clojure.core$load_one.invokeStatic(core.clj:5848)
	at clojure.core$load_one.invoke(core.clj:5843)
	at clojure.core$load_lib$fn__6493.invoke(core.clj:5888)
	at clojure.core$load_lib.invokeStatic(core.clj:5887)
	at clojure.core$load_lib.doInvoke(core.clj:5868)
	at clojure.lang.RestFn.applyTo(RestFn.java:142)
	at clojure.core$apply.invokeStatic(core.clj:659)
	at clojure.core$load_libs.invokeStatic(core.clj:5925)
	at clojure.core$load_libs.doInvoke(core.clj:5909)
	at clojure.lang.RestFn.applyTo(RestFn.java:137)
	at clojure.core$apply.invokeStatic(core.clj:659)
	at clojure.core$require.invokeStatic(core.clj:5947)
	at clojure.core$require.doInvoke(core.clj:5947)
	at clojure.lang.RestFn.invoke(RestFn.java:408)
	at user$eval2665.invokeStatic(build.clj:1)
	at user$eval2665.invoke(build.clj:1)
	at clojure.lang.Compiler.eval(Compiler.java:7062)
	at clojure.lang.Compiler.load(Compiler.java:7514)
	at clojure.lang.Compiler.loadFile(Compiler.java:7452)
	at clojure.main$load_script.invokeStatic(main.clj:278)
	at clojure.main$script_opt.invokeStatic(main.clj:338)
	at clojure.main$script_opt.invoke(main.clj:333)
	at clojure.main$main.invokeStatic(main.clj:424)
	at clojure.main$main.doInvoke(main.clj:387)
	at clojure.lang.RestFn.applyTo(RestFn.java:137)
	at clojure.lang.Var.applyTo(Var.java:702)
	at clojure.main.main(main.java:37)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at clojure.lang.Reflector.invokeMatchingMethod(Reflector.java:93)
	at clojure.lang.Reflector.invokeStaticMethod(Reflector.java:207)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at clojure.lang.Reflector.invokeMatchingMethod(Reflector.java:93)
	at clojure.lang.Reflector.invokeStaticMethod(Reflector.java:207)
	at user$eval2650.invokeStatic(form-init5146558131879438430.clj:1)
	at user$eval2650.invoke(form-init5146558131879438430.clj:1)
	at clojure.lang.Compiler.eval(Compiler.java:7062)
	at clojure.lang.Compiler.eval(Compiler.java:7052)
	at clojure.lang.Compiler.load(Compiler.java:7514)
	at clojure.lang.Compiler.loadFile(Compiler.java:7452)
	at clojure.main$load_script.invokeStatic(main.clj:278)
	at clojure.main$init_opt.invokeStatic(main.clj:280)
	at clojure.main$init_opt.invoke(main.clj:280)
	at clojure.main$initialize.invokeStatic(main.clj:311)
	at clojure.main$null_opt.invokeStatic(main.clj:345)
	at clojure.main$null_opt.invoke(main.clj:342)
	at clojure.main$main.invokeStatic(main.clj:424)
	at clojure.main$main.doInvoke(main.clj:387)
	at clojure.lang.RestFn.applyTo(RestFn.java:137)
	at clojure.lang.Var.applyTo(Var.java:702)
	at clojure.main.main(main.java:37)
Caused by: java.lang.ClassNotFoundException: javax.xml.bind.DatatypeConverter
	at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:466)
	at clojure.lang.DynamicClassLoader.findClass(DynamicClassLoader.java:69)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:566)
	at clojure.lang.DynamicClassLoader.loadClass(DynamicClassLoader.java:77)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:499)
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Class.java:374)
	at clojure.lang.RT.classForName(RT.java:2204)
	at clojure.lang.RT.classForNameNonLoading(RT.java:2217)
	at cljs.util$eval2877$loading__6434__auto____2878.invoke(util.cljc:9)
	at cljs.util$eval2877.invokeStatic(util.cljc:9)
	at cljs.util$eval2877.invoke(util.cljc:9)
	at clojure.lang.Compiler.eval(Compiler.java:7062)
	at clojure.lang.Compiler.eval(Compiler.java:7051)
	at clojure.lang.Compiler.load(Compiler.java:7514)
	... 92 more
```
